language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init 
  - git config user.name "travis ci"
  - git config user.email "travis@163.com"
  - git add .
  - git commit -m "自动部署"
  - git push --force --quiet "https://${GitHub_Token}@${GH_REF}" master:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/sslf/sslf.github.io